#!/bin/bash
# Complete Database Restoration Script for Portainer

echo "=== DATABASE RESTORATION GUIDE ==="
echo ""
echo "Step 1: Copy backup to Postgres container"
echo "Run this on your LOCAL machine (not in container):"
echo ""
echo "  docker cp supabase_backup.sql.gz nadanaloga-main-postgres:/tmp/"
echo ""
echo "Step 2: Enter the Postgres container"
echo ""
echo "  docker exec -it nadanaloga-main-postgres bash"
echo ""
echo "Step 3: Drop and recreate database (IN CONTAINER)"
echo ""
echo "  psql -U nadanaloga_user -d postgres"
echo ""
echo "Then in psql run:"
echo ""
echo "  DROP DATABASE IF EXISTS nadanaloga;"
echo "  CREATE DATABASE nadanaloga;"
echo "  \\q"
echo ""
echo "Step 4: Restore from backup (IN CONTAINER)"
echo ""
echo "  gunzip -c /tmp/supabase_backup.sql.gz | psql -U nadanaloga_user -d nadanaloga"
echo ""
echo "Step 5: Add missing columns (IN CONTAINER)"
echo ""
echo "  psql -U nadanaloga_user -d nadanaloga < /path/to/RESTORE-DATABASE.sql"
echo ""
echo "OR copy the SQL and paste into psql"
echo ""
echo "Step 6: Restart app container"
echo ""
echo "  In Portainer: Containers → nadanaloga-main-app → Restart"
echo ""
